services:
  # DATABASE: The Postgres Engine
  db:
    image: postgres:15-alpine
    container_name: synapse-db
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - synapse-network

  # BACKEND:
  backend:
    build: ./flashcards-api
    container_name: synapse-backend
    ports:
      - "${API_PORT}:8080"
    depends_on:
      - db
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/${DB_NAME}
      SPRING_DATASOURCE_USERNAME: ${DB_USER}
      SPRING_DATASOURCE_PASSWORD: ${DB_PASSWORD}
      JWT_SECRET: ${JWT_SECRET}
    networks:
      - synapse-network

  # FRONTEND:
  frontend:
    build: ./flashcards-ui
    container_name: synapse-frontend
    ports:
      - "${FRONTEND_PORT}:80"
    depends_on:
      - backend
    networks:
      - synapse-network

networks:
  synapse-network:
    driver: bridge

volumes:
  postgres_data: