spring.application.name=flashcards-api
# Database Config
spring.datasource.url=${SPRING_DATASOURCE_URL}
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}
# Jpa / hibernate configuration
spring.jpa.hibernate.ddl-auto=${SPRING_JPA_HIBERNATE_DDL_AUTO}
# Security Config
app.security.jwt.secret=${JWT_SECRET}